// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1UofoSe6cp1U9MGn7IV3a0JucSBvp2Q',
    appId: '1:972214616753:web:93e7ee47516e368d705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    authDomain: 'simplist-88038.firebaseapp.com',
    storageBucket: 'simplist-88038.firebasestorage.app',
    measurementId: 'G-RC0JK73NGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK84q9h5FJo9-G3vXxNmKMkCCInoitsao',
    appId: '1:972214616753:android:b39cf8ef304b1b8a705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    storageBucket: 'simplist-88038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2lS5p516mL2hpVYAe7F7xYKKJ1n3km0',
    appId: '1:972214616753:ios:cef739a5a3120b15705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    storageBucket: 'simplist-88038.firebasestorage.app',
    iosBundleId: 'com.example.practice5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2lS5p516mL2hpVYAe7F7xYKKJ1n3km0',
    appId: '1:972214616753:ios:cef739a5a3120b15705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    storageBucket: 'simplist-88038.firebasestorage.app',
    iosBundleId: 'com.example.practice5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1UofoSe6cp1U9MGn7IV3a0JucSBvp2Q',
    appId: '1:972214616753:web:2ff8b7893e739343705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    authDomain: 'simplist-88038.firebaseapp.com',
    storageBucket: 'simplist-88038.firebasestorage.app',
    measurementId: 'G-ZWK5BMS33M',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBu1UofoSe6cp1U9MGn7IV3a0JucSBvp2Q',
    appId: '1:972214616753:web:2ff8b7893e739343705890',
    messagingSenderId: '972214616753',
    projectId: 'simplist-88038',
    authDomain: 'simplist-88038.firebaseapp.com',
    storageBucket: 'simplist-88038.firebasestorage.app',
    measurementId: 'G-ZWK5BMS33M',
  );
}
