name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../../upload-keystore.jks" >> android/key.properties

      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop

      - name: Allow older CMake projects
        run: echo "CMAKE_POLICY_VERSION_MINIMUM=3.5" >> $env:GITHUB_ENV

      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: build/windows/x64/runner/Release/

  release:
    needs: [build-apk, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./apk
      - uses: actions/download-artifact@v4
        with:
          name: app-windows
          path: ./windows
      - name: Zip Windows build
        run: cd windows && zip -r ../app-windows.zip . && cd ..
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            apk/app-release.apk
            app-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}